# Generated by Django 5.1.3 on 2025-03-05 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='web3sports.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='web3sports.team')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='web3sports.league')),
            ],
        ),
        migrations.CreateModel(
            name='GameLineupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter')], max_length=20)),
                ('lineup_order', models.PositiveIntegerField()),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_lineup_entries', to='web3sports.game')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_entries', to='web3sports.game')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_lineup_entries', to='web3sports.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web3sports.player')),
            ],
            options={
                'ordering': ['lineup_order'],
                'unique_together': {('game', 'player', 'home_team', 'away_team')},
            },
        ),
    ]
