# Generated by Django 5.1.3 on 2025-03-05 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3sports', '0002_game_gamelineupentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='web3sports.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='web3sports.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
